<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Mailmaster gestion de mail">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Mailmaster</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="place-center">
      <main>
        <form method="post">
          <input class="btn" type="text" name="newUserMail" id="newUserMail">
          <input class="btn" type="password" name="newUserPassword" id="newUserPassword">
          <input class="btn btn--primary" type="submit" name="portalsubmit" id="newUserSubmit" value="Créer un nouveau mail">
        </form>
      </main>
  </div>
  <footer class="site-footer">
    <?php require_once('footer.phtml') ?>
  </footer>
  <script type="text/javascript" src="js/script.js"></script>
</body>
</html>
